version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql:cached
      - ./migrations:/migrations
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: wikipedia
      MYSQL_USER: wiki
      MYSQL_PASSWORD: wiki
      MYSQL_ROOT_PASSWORD: wikiwiki
  langlinks-server:
    depends_on:
      - db
    build: .
    volumes:
      - .:/app:cached
    networks:
      - default
      - langlinks
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MYSQL_DATABASE: wikipedia
      MYSQL_USER: wiki
      MYSQL_PASSWORD: wiki

networks:
  langlinks:
    external: true